# Generated by Django 5.1.6 on 2025-02-13 16:56

import datetime
import django.core.validators
import django.db.models.deletion
import ficha.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='cliente',
            fields=[
                ('rut', models.CharField(help_text='Formato: XXXXXXXX-X', max_length=10, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message='El RUT debe estar en formato XXXXXXXX-X', regex='^\\d{7,8}-[\\dkK]$')])),
                ('nombre', models.CharField(max_length=150)),
                ('apellido', models.CharField(max_length=150)),
                ('direccion', models.CharField(max_length=200)),
                ('tipo_producto', models.CharField(max_length=100)),
                ('tipo_cliente', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='ejecutivo',
            fields=[
                ('rut_ejecutivo', models.CharField(help_text='Formato: 20222777-X', max_length=10, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message='El RUT debe estar en formato XXXXXXXX-X', regex='^\\d{7,8}-[\\dkK]$')])),
                ('nombre_ejecutivo', models.CharField(max_length=100)),
                ('username_ejecutivo', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Errores_agravante',
            fields=[
                ('id_base', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_parametro', models.CharField(max_length=100)),
                ('tipo_error', models.CharField(max_length=100)),
                ('tipo_cliente', models.CharField(max_length=20)),
                ('nota', models.CharField(default='', max_length=20)),
                ('puntaje', models.DecimalField(decimal_places=1, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='oficina',
            fields=[
                ('cui', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='CUI')),
                ('nombre_ofi', models.CharField(max_length=50, verbose_name='Nombre Oficina')),
            ],
        ),
        migrations.CreateModel(
            name='Parametro',
            fields=[
                ('id_parametro', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_parametro', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Pilares',
            fields=[
                ('id_pilar', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='sucursal',
            fields=[
                ('cod_sucursal', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Codigo Sucursal')),
                ('nombre_suc', models.CharField(max_length=50, verbose_name='Nombre Sucursal')),
                ('aprobador', models.CharField(max_length=30, verbose_name='Nombre aprobador')),
                ('n_oportunidad', models.CharField(max_length=100, verbose_name='N° Oportunidad')),
                ('cant_ejecutivo', models.CharField(default='', max_length=5, verbose_name='Cantidad Ejecutivos')),
            ],
        ),
        migrations.CreateModel(
            name='filtro_revision',
            fields=[
                ('id_filtro', models.AutoField(primary_key=True, serialize=False)),
                ('Ejec.Responsable', models.CharField(max_length=40, verbose_name=ficha.models.ejecutivo)),
                ('username_ejecutivo', models.CharField(max_length=20, verbose_name=ficha.models.ejecutivo)),
                ('tipo_cliente', models.CharField(max_length=10, verbose_name=ficha.models.cliente)),
                ('nombre_suc', models.CharField(max_length=40, verbose_name=ficha.models.sucursal)),
                ('tipo_producto', models.CharField(max_length=20, verbose_name=ficha.models.cliente)),
                ('monto_solicitado', models.IntegerField(default=0, verbose_name='monto solicitado')),
                ('rut', models.CharField(max_length=10, verbose_name=ficha.models.cliente)),
                ('num_revision', models.CharField(max_length=10, verbose_name='Revisión N°: ')),
                ('cui', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ficha.oficina')),
            ],
        ),
        migrations.CreateModel(
            name='oportunidad',
            fields=[
                ('id_oportunidad', models.AutoField(primary_key=True, serialize=False)),
                ('username_ejecutivo', models.CharField(default='', max_length=20, verbose_name='Log Ejecutivo')),
                ('inconsistencia', models.CharField(max_length=200)),
                ('monto_solicitado', models.IntegerField(default=0, verbose_name='monto solicitado')),
                ('proceso_credito', models.CharField(max_length=20)),
                ('pauta_evaluacion', models.CharField(max_length=30)),
                ('anio_mes', models.DateField(default=datetime.date.today, verbose_name='Fecha')),
                ('canal', models.CharField(default='', max_length=5)),
                ('prod_eval', models.CharField(max_length=50, verbose_name='producto evaluado')),
                ('cui', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='ficha.oficina')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roles', models.CharField(max_length=50)),
                ('foto', models.ImageField(default='default.jpg', upload_to='static/img')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
