# Generated by Django 5.1.6 on 2025-02-14 18:14

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ejecutivo',
            fields=[
                ('rut_ejecutivo', models.CharField(help_text='Formato: 20222777-X', max_length=10, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message='El RUT debe estar en formato XXXXXXXX-X', regex='^\\d{7,8}-[\\dkK]$')])),
                ('nombre_ejecutivo', models.CharField(max_length=100)),
                ('username_ejecutivo', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Errores_agravante',
            fields=[
                ('id_base', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_parametro', models.CharField(max_length=100)),
                ('tipo_error', models.CharField(max_length=100)),
                ('tipo_cliente', models.CharField(max_length=20)),
                ('nota', models.CharField(max_length=20)),
                ('puntaje', models.DecimalField(decimal_places=1, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='oficina',
            fields=[
                ('cui', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='CUI')),
                ('nombre_ofi', models.CharField(max_length=50, verbose_name='Nombre Oficina')),
            ],
        ),
        migrations.CreateModel(
            name='Parametro',
            fields=[
                ('id_parametro', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_parametro', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Pilares',
            fields=[
                ('id_pilar', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='sucursal',
            fields=[
                ('cod_sucursal', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Codigo Sucursal')),
                ('nombre_suc', models.CharField(max_length=50, verbose_name='Nombre Sucursal')),
                ('aprobador', models.CharField(max_length=30, verbose_name='Nombre aprobador')),
                ('n_oportunidad', models.CharField(max_length=100, verbose_name='N° Oportunidad')),
                ('cant_ejecutivo', models.CharField(max_length=5, verbose_name='Cantidad Ejecutivos')),
            ],
        ),
        migrations.CreateModel(
            name='cliente',
            fields=[
                ('rut', models.CharField(help_text='Formato: XXXXXXXX-X', max_length=10, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message='El RUT debe estar en formato XXXXXXXX-X', regex='^\\d{7,8}-[\\dkK]$')])),
                ('nombre', models.CharField(max_length=150)),
                ('apellido', models.CharField(max_length=150)),
                ('direccion', models.CharField(max_length=200)),
                ('tipo_producto', models.CharField(max_length=100)),
                ('tipo_cliente', models.CharField(max_length=40)),
                ('oficina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ficha.oficina')),
            ],
        ),
        migrations.CreateModel(
            name='FiltroRevision',
            fields=[
                ('id_filtro', models.AutoField(primary_key=True, serialize=False)),
                ('monto_solicitado', models.CharField(max_length=30)),
                ('n_revision', models.IntegerField(verbose_name='N° Revision')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ficha.cliente')),
                ('ejecutivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ficha.ejecutivo')),
                ('oficina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ficha.oficina')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ficha.sucursal')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roles', models.CharField(max_length=50)),
                ('foto', models.ImageField(default='default.jpg', upload_to='static/img')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
