# Generated by Django 5.1.6 on 2025-02-14 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sucursal',
            name='n_oportunidad',
        ),
    ]
