# Generated by Django 5.1.6 on 2025-02-17 18:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0002_remove_sucursal_n_oportunidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='rut',
            field=models.CharField(help_text='Formato: 20222777-X', max_length=10, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message='El RUT debe estar en formato 20222777-X', regex='^\\d{7,8}-[\\dkK]$')]),
        ),
        migrations.AlterField(
            model_name='ejecutivo',
            name='rut_ejecutivo',
            field=models.CharField(help_text='Formato: 20222777-X', max_length=10, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message='El RUT debe estar en formato 20222777-X', regex='^\\d{7,8}-[\\dkK]$')]),
        ),
    ]
