# Generated by Django 5.1.6 on 2025-02-18 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0004_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
