# Generated by Django 5.1.6 on 2025-02-18 15:26

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0005_delete_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roles', models.CharField(max_length=50)),
                ('foto', models.ImageField(default='default.jpg', upload_to='static/img')),
                ('ci', models.CharField(help_text='Formato: 20222777-X', max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='El RUT debe estar en formato 20222777-X', regex='^\\d{7,8}-[\\dkK]$')])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
