# Generated by Django 5.1.6 on 2025-02-21 13:58

import django.core.validators
import ficha.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0006_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='nombre',
        ),
        migrations.AlterField(
            model_name='ejecutivo',
            name='rut_ejecutivo',
            field=models.CharField(help_text='Formato: 20222778', max_length=8, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message='El RUT debe estar en formato 20222778', regex='^\\d{7,8}$'), ficha.models.val_rut_ejecutivo]),
        ),
    ]
