# Generated by Django 5.1.6 on 2025-02-26 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0007_remove_cliente_apellido_remove_cliente_direccion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametro',
            name='id_pilar',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='ficha.pilares'),
        ),
    ]
