# Generated by Django 5.1.6 on 2025-02-27 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0009_rename_id_base_errores_agravante_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='errores_agravante',
            name='nombre_error',
        ),
        migrations.RemoveField(
            model_name='parametro',
            name='error_agravante',
        ),
        migrations.AddField(
            model_name='parametro',
            name='errores_agravantes',
            field=models.ManyToManyField(blank=True, to='ficha.errores_agravante'),
        ),
        migrations.AlterField(
            model_name='parametro',
            name='pilar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ficha.pilares'),
        ),
    ]
