# Generated by Django 5.1.6 on 2025-02-28 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0010_remove_errores_agravante_nombre_error_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('nota_final', models.DecimalField(decimal_places=2, max_digits=3)),
                ('clasificacion', models.CharField(max_length=50)),
                ('ejecutivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ficha.ejecutivo')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleEvaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.DecimalField(decimal_places=2, max_digits=3)),
                ('errores_agravantes', models.ManyToManyField(blank=True, to='ficha.errores_agravante')),
                ('parametro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ficha.parametro')),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ficha.evaluacion')),
            ],
        ),
    ]
