# Generated by Django 5.1.6 on 2025-03-10 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0011_evaluacion_detalleevaluacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registro_materialidad',
            fields=[
                ('id_registro', models.AutoField(primary_key=True, serialize=False)),
                ('rut', models.CharField(max_length=12)),
                ('dv', models.CharField(max_length=1)),
                ('log_fecha_registro', models.DateTimeField()),
                ('login_creador', models.CharField(max_length=100)),
                ('nombre_creador', models.CharField(max_length=100)),
                ('oficina_ejecutivo', models.CharField(max_length=100)),
                ('cui', models.CharField(max_length=20)),
                ('etapa_venta_actual', models.CharField(max_length=100)),
                ('inconsistencia', models.CharField(max_length=100)),
                ('max_prod_rgo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monto_oferta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('proceso_credito', models.CharField(max_length=100)),
                ('pauta_evaluacion', models.CharField(max_length=100)),
                ('decision_final', models.CharField(max_length=100)),
                ('ano_mes', models.CharField(max_length=6)),
                ('canal', models.CharField(max_length=100)),
                ('prod_eval', models.CharField(max_length=100)),
                ('nombre_ejecutivo', models.CharField(max_length=100)),
                ('rut_ejecutivo', models.CharField(max_length=12)),
                ('mes_numero', models.IntegerField()),
                ('mes_nombre', models.CharField(max_length=20)),
                ('codigo_suc', models.CharField(max_length=10)),
                ('nombre_suc', models.CharField(max_length=100)),
                ('aprobador', models.CharField(max_length=100)),
                ('n_oportunidad', models.CharField(max_length=20)),
            ],
        ),
    ]
