# Generated by Django 5.1.6 on 2025-03-10 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0012_registro_materialidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro_materialidad',
            name='log_fecha_registro',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='registro_materialidad',
            name='mes_numero',
            field=models.CharField(max_length=12),
        ),
    ]
