# Generated by Django 5.1.6 on 2025-03-10 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0013_alter_registro_materialidad_log_fecha_registro_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registro_materialidad',
            name='max_prod_rgo',
        ),
    ]
